Support task to Resolve names/IPs on Unix/Linux
squaredup/Community.DataOnDemand.MP pull request #13
Opened 2016-11-15 16:41 UTC by shadeon

This PR adds a unix task that allows you to resolve a list of IP Addresses and/or names into complete lookup records from the target server's perspective.

## Changes

- Added a probe module that supports querying DNS on the local machine with a list of targets, as supplied via a parameter.
- Added a task that exposes the above probe, where users can specify addresses via the override-able parameter.

## Issues Addressed
#9
## Breaking Changes
None.

2016-11-15 16:50 UTC, clarkd requested changes

2016-11-15 16:50 UTC, clarkd commented on ManagementPacks/Community.DataOnDemand.Unix/Scripts/ResolveAddress.pl
> +            $ipaddr = inet_ntoa(inet_aton($query));
What's the benefit if doing inet_ntoa only to do the opposite again?

2016-11-15 16:50 UTC, clarkd commented on ManagementPacks/Community.DataOnDemand.Unix/Modules/Probe.ResolveAddress.mpx
> +          <Description>IP addresses or name to resolve, as a comma seperated list.</Description>
'names'

2016-11-15 22:44 UTC, DavidR91 approved these changes
Only suggestion would be commentary in the Perl file (see comment)

2016-11-15 22:44 UTC, DavidR91 commented on ManagementPacks/Community.DataOnDemand.Unix/Scripts/ResolveAddress.pl
> +    my (@octets) = $value =~ /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/;
I feel like this line, along with 48 and 49 could do with a small comment just explaining roughly what their effects  [on each octet] are  (esp. given nobody really knows Perl)

2016-11-16 13:33 UTC, clarkd approved these changes

2016-11-16 13:55 UTC, merged