Support Netstat Task on Unix
squaredup/Community.DataOnDemand.MP pull request #6
Opened 2016-11-03 15:41 UTC by shadeon

This PR provides support for getting CSV data from Unix/Linux hosts commonly found in SCOM.

## Changes
- Added a Unix management pack to the solution so we can provide functionality to nix workloads without forcing the import of Unix Library MPs for everyone who wants to use the Data On Demand MP set.
- Added a SCOM task for getting Netstat data that is supported on RHEL, Ubuntu, SLES, CentOS and Oracle linux.

## Issues Addressed
- #1 

## Breaking Changes
None.

2016-11-03 23:33 UTC, clarkd requested changes

2016-11-03 23:33 UTC, clarkd commented on ManagementPacks/Community.DataOnDemand.Unix/Modules/Probe.GetNetstatCsv.mpx
> +          <Description>Displays established TCP connections collected via netstat -ano</Description>
" -ano" ??

2016-11-03 23:33 UTC, clarkd commented on ManagementPacks/Community.DataOnDemand.Unix/Scripts/GetNetstatCSV.sh
> +case "$Format" in
The tabulation here looks screwy?

2016-11-03 23:33 UTC, clarkd commented on ManagementPacks/Community.DataOnDemand.Unix/Scripts/GetNetstatCSV.sh
> +        gsub(/:/, ",")
Is gsub available on all systems? Ruby?

2016-11-04 08:08 UTC, shadeon commented on ManagementPacks/Community.DataOnDemand.Unix/Scripts/GetNetstatCSV.sh
> +        gsub(/:/, ",")
The g stands for global not GNU, the gsub function is part of the POSIX awk standard.

2016-11-04 08:09 UTC, shadeon commented on ManagementPacks/Community.DataOnDemand.Unix/Modules/Probe.GetNetstatCsv.mpx
> +          <Description>Displays established TCP connections collected via netstat -ano</Description>
I'll correct this, as those are the windows command line options.  Should be -tpn

2016-11-04 08:16 UTC, shadeon commented on ManagementPacks/Community.DataOnDemand.Unix/Scripts/GetNetstatCSV.sh
> +case "$Format" in
Corrected, don't know why VS used tabs for those few lines..

2016-11-04 09:43 UTC, clarkd commented on ManagementPacks/Community.DataOnDemand.Unix/Scripts/GetNetstatCSV.sh
> +case "$Format" in
Thanks

2016-11-04 09:44 UTC, clarkd approved these changes

2016-11-04 13:18 UTC, merged